name: Publish Website

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v2
        - name: Build
          run: swift run PeteSchaffner --removeDrafts
    publish:
        - uses: ./.github/actions/sync