name: Publish Website

on:
    push:
        branches: [ master ]

jobs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
        run: swift run PeteSchaffner --removeDrafts
    - uses: ./.github/actions/sync