name: Publish Website

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build website
              run: swift run PeteSchaffner --removeDrafts
            - name: Upload built site files
              uses: actions/upload-artifact@v1
              with:
                  name: Output
                  path: Output
    publish:
        runs-on: ubuntu-latest
        needs: build
        env:
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        steps:
            - name: Download built site files from build job
              uses: actions/download-artifact@v1
              with:
                  name: Output
            - uses: ./.github/actions/sync