name: Publish Website

on:
    push:
        branches: [ master ]

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        steps:
            - uses: actions/checkout@v2
            - name: Setup SSH key
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan 46.226.107.32 >> ~/.ssh/known_hosts
                  ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                  ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
            - name: Publish website
              run: make publish