name: Publish Website

on:
    push:
        branches: [ master ]

jobs:
    publish:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build website
              run: swift run PeteSchaffner --removeDrafts
            - name: Start up SSH agent
              run: eval "$(ssh-agent -s)"
            - name: Add SSH key
              run: ssh-add - <<< "${{ secrets.PRIVATE_KEY }}"
            - name: Publish website
              run: rsync --recursive --delete -e 'ssh -o StrictHostKeyChecking=no' $GITHUB_WORKSPACE/Output/ pete@peteschaffner.com:www