name: Publish Website

on:
    push:
        branches: [ master ]

jobs:
    publish:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build website
              run: swift run PeteSchaffner --removeDrafts
            - run: eval "$(ssh-agent -s)"
            # - run: echo "${{ secrets.PRIVATE_KEY }}" | ssh-add
            - run: rsync --recursive --delete $GITHUB_WORKSPACE/Output pete@peteschaffner.com:www
    # publish:
    #     runs-on: ubuntu-latest
    #     needs: build
    #     env:
    #         PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
    #     steps:
    #         - name: Download built site files from build job
    #           uses: actions/download-artifact@v1
    #           with:
    #               name: Output
    #         - uses: actions/checkout@v2
    #         - uses: ./.github/actions/sync