name: Publish Website

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Build website
              run: swift run PeteSchaffner --removeDrafts
    publish:
        runs-on: ubuntu-latest
        env:
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        steps:
            - uses: ./.github/actions/sync